name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest  # Install pytest

      - name: Run tests
        run: |
          echo "def test_sample(): assert True" > test_sample.py  # Create a simple test
          pytest test_sample.py  # Run the test
